/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zaliczenie.sesjaJava;

import java.util.ArrayDeque;
import java.util.Deque;

enum Discography {
    Prequelle, Infestissumam, Meliora,
    Cirice, Rats,
    Popestar
    }

public class App {

    Deque<Ghosts> GhostsDeque = new ArrayDeque<>();

    public static void main(String[] args) {

        App app = new App();

        app.trackList();
        app.playPlayList();

        System.out.println("");
        System.out.println("Prequelle is " + app.records(Discography.Prequelle));
        System.out.println("Cirice is " + app.records(Discography.Cirice));
        System.out.println("Popestar is " + app.records(Discography.Popestar));
        System.out.println("Rats is "+ app.records(Discography.Rats));
    }


    String records(Discography title) {

        String CD = "";

        switch (title) {
            case Prequelle, Infestissumam, Meliora -> CD = "full record.";
            case Cirice, Rats -> CD = "teaser record.";
            case Popestar -> CD = "single record.";
            default -> CD = "other type of record.";
        }
        return CD;
    }

    void trackList() {
        System.out.println("");
        System.out.println(Ghosts.informacja);
        for (Ghosts ghosts : Ghosts.values())
            System.out.println(ghosts.songInfo());


        GhostsDeque.offer(Ghosts.Prequelle);
        GhostsDeque.offer(Ghosts.Meliora);
        GhostsDeque.offer(Ghosts.Infestissumam);
        System.out.println("");

    }

    void playPlayList() {
        while (!GhostsDeque.isEmpty()) {
            Ghosts ghosts = GhostsDeque.poll();
            ghosts.playPlayList();
        }
    }
}




